//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public int PassengerID { get; set; }
        public string PassengerName { get; set; }
        public string PassengerEmail { get; set; }
        public string PassengerPhone { get; set; }
        public System.DateTime JourneyDate { get; set; }
        public string ImageName { get; set; }
        public string ImageUrl { get; set; }
        public int TrainNo { get; set; }
        public int ClassID { get; set; }
        public int RouteID { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Train Train { get; set; }
        public virtual Route Route { get; set; }
    }
}
